# Generated by Django 5.0 on 2023-12-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_page_options_page_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
